### DISCUSSION TITLE
fix to readme required it seems

### DISCUSSION THREAD

**Discussion by DaReBeL** [etf1/kafka-message-scheduler#37] [General]
Hi!
Kindly asking you to mention somehow on the readme what the scheduler-epoch value HAVE to be a string but not a long value, as it looking like in example currently. I just spent almost two days trying to figure out why nothing is working, and the reason was that the longs were passed instead of strings :) So it may help someone I hope.

<img width="695" alt="image" src="https://user-images.githubusercontent.com/91911898/176900461-c8e4f6e5-1b1a-44ac-ac08-3ddef0b826b8.png">

Thank you!

**Comment by fkarakas** [comment]
Hello @DaReBeL sorry to hear that :(
I will update the readme and add double quote so it will be clear, WDYT ?
```
Headers:
    scheduler-epoch: "1893456000"
    scheduler-target-topic: "online-videos"
    scheduler-target-key: "vid1"
    customer-header: "dummy"
Timestamp: 1607918336
Key: "vid1-online"
Value: "video 1"
```
